server.port=8080

spring.application.name=routePlaner
spring.datasource.url=jdbc:postgresql: -- YOUR DATABASE
spring.datasource.username= -- LOGIN
spring.datasource.password= -- PASS
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Opcjonalne logowanie zapyta? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.springframework.security=DEBUG
