server.port=8080

spring.application.name=routePlaner
spring.datasource.url=jdbc:postgresql://psql01.mikr.us/db_w165
spring.datasource.username=w165
spring.datasource.password=9625_426b03
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Opcjonalne logowanie zapyta? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.springframework.security=DEBUG