POST http://localhost:8080/api/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzIwODUxMywiZXhwIjoxNzM3Mjk0OTEzfQ.jENBx__D8_Lr9MUgY5Rd-2R6J6emurhWbCtHy21xxRg
Content-Type: application/json

{
  "name": "Truck 6",
  "capacity": 5000,
  "type": "truck",
  "user":{
  "id": 8
}
}